### ISSUE TITLE
[FEATURE REQUEST]Sticker Library Support

### ISSUE THREAD

**Issue by EncryptedCicada** [vidit135g/Sticker_Maker#1]
I've been using this app for a while now and it has been going great for me. Definitely the cleanest and the best sticker maker out there. The only feature I feel missing (or I'm yet to discover if it's already in the app) is the ability to browse through the sticker library which includes all the stickers sent and received on whatsapp and add them to our own sticker packs with the ability to edit them as well. It's not a necessity for me as I'll continue using the app but considering many people would like that feature, I'd love to see it implemented in this app. So far, I've only seen one outdated app that has that feature (in somewhat working conditions) and that is this [Sticker Manager]([https://play.google.com/store/apps/details?id=com.luisantos.stickermanager). Hope this helps in the future and thanks a lot for a no distractions sticker maker.

**Comment by EncryptedCicada** [comment]
I missed the link to that app earlier
https://play.google.com/store/apps/details?id=com.luisantos.stickermanager

**Comment by vidit135g** [comment]
That's a pretty decent feature, thanks for the suggestion. I'll start working on it and let you know when it's done. 

btw, thanks for using the app 🙂✌️
